"""empty message

Revision ID: f1e96ddf7725
Revises: add9c6e18e95
Create Date: 2022-02-17 15:36:34.563599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e96ddf7725'
down_revision = 'add9c6e18e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('subject', sa.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
